### ISSUE TITLE
Tabbing or spaces in mark up add extra spans - Bug? Maybe not

### ISSUE THREAD

**Issue by LindenWalsh** [davatron5000/Lettering.js#42]
I'm not sure if this is a bug or not but it confused me for a good 10 minutes.

I've created a pen to highlight the problem I had: http://cdpn.io/petGF

Basically, I had my div set up with an id to target with lettering.js and inside the div I was using PHP to echo a value, I mistakenly added tabbing and went to a new line to make my code look nice and stuff but that seems to make lettering add extra spans. 

Removing the tabs fixed it, as I said though I don't know if this is a bug or if I was just using it wrong.

**Comment by ssr1368** [comment]
Hi fellows,
I solved this bug with:

if(!($(event.target).html().charAt(0)==='<'))
{
//do whatever you want to
}

Best,
Sergi

**Comment by davatron5000** [comment]
I just made a quick pen where you can `$.trim()` the whitespace out of the `text()`. 

http://codepen.io/davatron5000/pen/WbMWmE?editors=101

```
$("#example_three").text( 
    $.trim(
      $("#example_three").text()
    )
).lettering();
```

I think (unless this is a super common problem), it might make sense to leave this outside of Lettering since it can be solved in a few lines of code and is unique to the CMS' output. If it keeps coming up, or there's a lot of consensus about adding it to the plugin, we can look at it.

I'll close, but reopen if you feel strongly it should be in Core.
